name: Build Website

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # - name: Run tests
      #   run: npm test

      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.PUSH_TOKEN }}git@github.com/AlicjaZub/rust_server.git temp-repo

      - name: Copy build output to target repo's out folder
        run: |
          rm -rf temp-repo/out
          mkdir -p temp-repo/out
          cp -r out/* temp-repo/out/

      - name: Commit and push changes
        run: |
          cd temp-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/
          git commit -m "Update out/ folder from $(date)" || echo "Nothing to commit"
          git push origin main
